/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marytts.tools.newinstall.gui;

import javax.swing.JFrame;

/**
 * 
 * @author Jonathan
 */
public class LogViewFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LogViewFrame
	 */
	public LogViewFrame() {
		setVisible(false);
		setAlwaysOnTop(false);
		setSize(500, 500);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setTitle("Log View");
		setResizable(true);
		setLocationByPlatform(true);
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
	 * this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextArea2.setEditable(false);
		jTextArea2.setColumns(20);
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jTextArea2.setWrapStyleWord(true);
		jScrollPane2.setViewportView(jTextArea2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane2,
				javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea2;

	// End of variables declaration//GEN-END:variables

	public void log(String logOutput) {

		// for (String oneLine : logOutput) {
		// this.jTextArea2.append(oneLine);
		// }
		this.jTextArea2.append(logOutput.concat("\n"));
		this.jTextArea2.setCaretPosition(jTextArea2.getDocument().getLength());

	}
}
