/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marytts.tools.newinstall;

import java.awt.Color;
import java.awt.FileDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;

import javax.swing.Box;
import javax.swing.BoxLayout;

import marytts.tools.newinstall.objects.Component;
import marytts.tools.newinstall.objects.VoiceComponent;

/**
 * 
 * @author Jonathan
 */
public class InstallerGUITmp extends javax.swing.JFrame {

	// data
	private Installer installer;

	/**
	 * Creates new form InstallerGUITmp
	 */
	public InstallerGUITmp(Installer installer) {
		if (installer == null) {
			System.err.println("Installer should not be null at this point!");
			installer = new Installer();
		}
		this.installer = installer;
		initComponents();
		fillComponentGroupPanels();
		addActionToAdvancedCheckBox();
		addActionToLogButton();
		addActionToMaryPathButton();
	}

	/* @formatter:off */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maryPathLabel = new javax.swing.JLabel();
        maryPathTextField = new javax.swing.JTextField();
        maryPathButton = new javax.swing.JButton();
        advancedCheckBox = new javax.swing.JCheckBox();
        logButton = new javax.swing.JButton();
        controlsPanel = new javax.swing.JPanel();
        localeBox = new javax.swing.JComboBox();
        localeLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox();
        genderBox = new javax.swing.JComboBox();
        genderLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusBox = new javax.swing.JComboBox();
        controlsSep = new javax.swing.JSeparator();
        componentTabbedPane = new javax.swing.JTabbedPane();
        voicesScrollPane = new javax.swing.JScrollPane();
        voicesGroupPanel = new javax.swing.JPanel();
        languagesScrollPane = new javax.swing.JScrollPane();
        languagesGroupPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Component Installer");
        setResizable(false);

        maryPathLabel.setText("Path to marytts installation folder:");

        maryPathButton.setText("dir");

        advancedCheckBox.setForeground(java.awt.Color.lightGray);
        advancedCheckBox.setText("advanced Mode");

        logButton.setText("show log view");

        controlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Use these controls to filter the list of available components"));

        localeBox.setMaximumRowCount(20);
        localeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        localeBox.setSelectedIndex(-1);

        localeLabel.setText("Locale");

        typeLabel.setText("Type");

        typeBox.setMaximumRowCount(20);
        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeBox.setSelectedIndex(-1);

        genderBox.setMaximumRowCount(20);
        genderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderBox.setSelectedIndex(-1);

        genderLabel.setText("Gender");

        statusLabel.setText("Status");

        statusBox.setMaximumRowCount(20);
        statusBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusBox.setSelectedIndex(-1);

        controlsSep.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout controlsPanelLayout = new javax.swing.GroupLayout(controlsPanel);
        controlsPanel.setLayout(controlsPanelLayout);
        controlsPanelLayout.setHorizontalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(localeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(localeLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsPanelLayout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(33, 33, 33)))
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(genderLabel))
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(statusLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlsPanelLayout.setVerticalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlsSep)
                    .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsPanelLayout.createSequentialGroup()
                            .addComponent(localeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(localeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsPanelLayout.createSequentialGroup()
                            .addComponent(typeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(controlsPanelLayout.createSequentialGroup()
                            .addComponent(genderLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(controlsPanelLayout.createSequentialGroup()
                            .addComponent(statusLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        componentTabbedPane.setPreferredSize(new java.awt.Dimension(477, 318));

        javax.swing.GroupLayout voicesGroupPanelLayout = new javax.swing.GroupLayout(voicesGroupPanel);
        voicesGroupPanel.setLayout(voicesGroupPanelLayout);
        voicesGroupPanelLayout.setHorizontalGroup(
            voicesGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        voicesGroupPanelLayout.setVerticalGroup(
            voicesGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        voicesScrollPane.setViewportView(voicesGroupPanel);

        componentTabbedPane.addTab("voices", voicesScrollPane);

        javax.swing.GroupLayout languagesGroupPanelLayout = new javax.swing.GroupLayout(languagesGroupPanel);
        languagesGroupPanel.setLayout(languagesGroupPanelLayout);
        languagesGroupPanelLayout.setHorizontalGroup(
            languagesGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        languagesGroupPanelLayout.setVerticalGroup(
            languagesGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        languagesScrollPane.setViewportView(languagesGroupPanel);

        componentTabbedPane.addTab("other", languagesScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(advancedCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(maryPathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maryPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maryPathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(controlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(componentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maryPathLabel)
                    .addComponent(maryPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maryPathButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advancedCheckBox)
                    .addComponent(logButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /* @formatter:on */

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		// try {
		// for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		// if ("Nimbus".equals(info.getName())) {
		// javax.swing.UIManager.setLookAndFeel(info.getClassName());
		// break;
		// }
		// }
		// } catch (ClassNotFoundException ex) {
		// java.util.logging.Logger.getLogger(InstallerGUITmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (InstantiationException ex) {
		// java.util.logging.Logger.getLogger(InstallerGUITmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (IllegalAccessException ex) {
		// java.util.logging.Logger.getLogger(InstallerGUITmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		// java.util.logging.Logger.getLogger(InstallerGUITmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		// }
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Installer installer = new Installer();
				new InstallerGUITmp(installer).setVisible(true);
			}
		});
	}

	private void addActionToLogButton() {
		this.logButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				java.awt.EventQueue.invokeLater(new Runnable() {
					public void run() {
						LogViewFrame logViewFrame = new LogViewFrame();
						new LogViewFrame().setVisible(true);
					}
				});
			}
		});
	}

	private void addActionToMaryPathButton() {
		this.maryPathButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				new FileDialog(InstallerGUITmp.this);
			}
		});
	}

	private void addActionToAdvancedCheckBox() {
		this.advancedCheckBox.setSelected(false);
		this.componentTabbedPane.setEnabledAt(1, false);
		this.advancedCheckBox.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					InstallerGUITmp.this.advancedCheckBox.setForeground(Color.BLACK);
					InstallerGUITmp.this.componentTabbedPane.setEnabledAt(1, true);
					InstallerGUITmp.this.componentTabbedPane.setForegroundAt(1, Color.BLACK);
					// java.awt.Component componentAt = InstallerGUITmp.this.componentTabbedPane.getComponentAt(1);
					// System.out.println(componentAt.toString());
				} else {
					InstallerGUITmp.this.advancedCheckBox.setForeground(Color.lightGray);
					InstallerGUITmp.this.componentTabbedPane.setEnabledAt(1, false);
					InstallerGUITmp.this.componentTabbedPane.setForegroundAt(1, Color.lightGray);
					InstallerGUITmp.this.componentTabbedPane.setSelectedIndex(0);
					// InstallerGUITmp.this.componentTabbedPane.getComponentAt(1).setVisible(true);
				}
			}
		});
	}

	/**
	 * TODO differentiate between mary components and lang components? TODO separate voiceComponentPanels from langs
	 * 
	 * @param componentGroupPanel
	 * @param componentTableModel
	 * @return
	 */
	private boolean fillComponentGroupPanels() {

		List<Component> resources = this.installer.getAvailableComponents();

		if (!(resources == null)) {
			for (Component oneComponent : resources) {
				if (oneComponent instanceof VoiceComponent) {
					this.voicesGroupPanel.setLayout(new BoxLayout(this.voicesGroupPanel, BoxLayout.Y_AXIS));
					VoiceComponentPanel voiceComponentPanel = new VoiceComponentPanel((VoiceComponent) oneComponent);
					this.voicesGroupPanel.add(voiceComponentPanel);
					this.voicesGroupPanel.add(Box.createVerticalGlue());
				} else {
					// TODO to which group panel -> how to distinguish?
					this.languagesGroupPanel.setLayout(new BoxLayout(this.languagesGroupPanel, BoxLayout.Y_AXIS));
					VoiceComponentPanel voiceComponentPanel = new VoiceComponentPanel(oneComponent);
					this.languagesGroupPanel.add(voiceComponentPanel);
					this.languagesGroupPanel.add(Box.createVerticalGlue());
				}
			}
			return true;
		}

		return false;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox advancedCheckBox;
	private javax.swing.JTabbedPane componentTabbedPane;
	private javax.swing.JPanel controlsPanel;
	private javax.swing.JSeparator controlsSep;
	private javax.swing.JComboBox genderBox;
	private javax.swing.JLabel genderLabel;
	private javax.swing.JPanel languagesGroupPanel;
	private javax.swing.JScrollPane languagesScrollPane;
	private javax.swing.JComboBox localeBox;
	private javax.swing.JLabel localeLabel;
	private javax.swing.JButton logButton;
	private javax.swing.JButton maryPathButton;
	private javax.swing.JLabel maryPathLabel;
	private javax.swing.JTextField maryPathTextField;
	private javax.swing.JComboBox statusBox;
	private javax.swing.JLabel statusLabel;
	private javax.swing.JComboBox typeBox;
	private javax.swing.JLabel typeLabel;
	private javax.swing.JPanel voicesGroupPanel;
	private javax.swing.JScrollPane voicesScrollPane;
	// End of variables declaration//GEN-END:variables
}
